import { Vehicle } from "../repositories/vehicle-repository"

export const mockData: Vehicle[] = [
  {
    price: 12999,
    make: "BMW",
    model: "1 SERIES",
    trim: "118d SE 5dr [Nav]",
    colour: "Alpine white",
    co2_level: 104,
    transmission: "Manual",
    fuel_type: "Diesel",
    engine_size: 1995,
    date_first_reg: new Date("2017-12-28"),
    mileage: 11271,
  },
  {
    price: 14699,
    make: "BMW",
    model: "1 SERIES",
    trim: "118d M Sport 5dr [Nav]",
    colour: "Melbourne red",
    co2_level: 114,
    transmission: "Manual",
    fuel_type: "Diesel",
    engine_size: 1995,
    date_first_reg: new Date("2017-12-28"),
    mileage: 13324,
  },
  {
    price: 15499,
    make: "BMW",
    model: "1 SERIES",
    trim: "118d M Sport 5dr [Nav/Servotronic]",
    colour: "Alpine white",
    co2_level: 120,
    transmission: "Manual",
    fuel_type: "Diesel",
    engine_size: 1995,
    date_first_reg: new Date("2017-12-28"),
    mileage: 20114,
  },
  {
    price: 13799,
    make: "BMW",
    model: "1 SERIES",
    trim: "116d SE Business 5dr [Nav/Servotronic]",
    colour: "Jet black",
    co2_level: 111,
    transmission: "Manual",
    fuel_type: "Diesel",
    engine_size: 1496,
    date_first_reg: new Date("2017-12-28"),
    mileage: 16759,
  },
]

